name: Project Publisher

on:
  workflow_call:
    inputs:
      profile:
        description: 'Build profile'
        type: string
        required: true
      version:
        description: 'Project version'
        type: string
        required: true
      semanticVersion:
        description: 'Project semantic version'
        type: string
        required: true
      hashVersion:
        description: 'Project hash commit'
        type: string
        required: true
      javaDist:
        description: 'Java distribution'
        type: string
        required: true
        default: 'temurin'
      javaVersion:
        description: 'Java version'
        type: string
        required: true
        default: '11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.9.0
        with:
          distribution: ${{ inputs.javaDist }}
          java-version: ${{ inputs.javaVersion }}
          cache: 'gradle'

      - name: Build
        shell: bash
        run: |
          ./gradlew clean build -x test \
              -Pprofile=${{ inputs.profile }} \
              -Pversion=${{ inputs.version }} \
              -PsemanticVersion=${{ inputs.semanticVersion }} \
              -PbuildBy="GitHub-Action" \
              -PbuildHash=${{ inputs.hashVersion }} \
              --no-daemon
